from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ErrorDetailsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _field=None, message=None):  # noqa: E501
        """ErrorDetailsInner - a model defined in OpenAPI

        :param _field: The _field of this ErrorDetailsInner.  # noqa: E501
        :type _field: str
        :param message: The message of this ErrorDetailsInner.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            '_field': str,
            'message': str
        }

        self.attribute_map = {
            '_field': 'field',
            'message': 'message'
        }

        self.__field = _field
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorDetailsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error_details_inner of this ErrorDetailsInner.  # noqa: E501
        :rtype: ErrorDetailsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _field(self) -> str:
        """Gets the _field of this ErrorDetailsInner.


        :return: The _field of this ErrorDetailsInner.
        :rtype: str
        """
        return self.__field

    @_field.setter
    def _field(self, _field: str):
        """Sets the _field of this ErrorDetailsInner.


        :param _field: The _field of this ErrorDetailsInner.
        :type _field: str
        """

        self.__field = _field

    @property
    def message(self) -> str:
        """Gets the message of this ErrorDetailsInner.


        :return: The message of this ErrorDetailsInner.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorDetailsInner.


        :param message: The message of this ErrorDetailsInner.
        :type message: str
        """

        self._message = message
