from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Links(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _self=None, next=None, prev=None):  # noqa: E501
        """Links - a model defined in OpenAPI

        :param _self: The _self of this Links.  # noqa: E501
        :type _self: str
        :param next: The next of this Links.  # noqa: E501
        :type next: str
        :param prev: The prev of this Links.  # noqa: E501
        :type prev: str
        """
        self.openapi_types = {
            '_self': str,
            'next': str,
            'prev': str
        }

        self.attribute_map = {
            '_self': 'self',
            'next': 'next',
            'prev': 'prev'
        }

        self.__self = _self
        self._next = next
        self._prev = prev

    @classmethod
    def from_dict(cls, dikt) -> 'Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Links of this Links.  # noqa: E501
        :rtype: Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> str:
        """Gets the _self of this Links.


        :return: The _self of this Links.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the _self of this Links.


        :param _self: The _self of this Links.
        :type _self: str
        """

        self.__self = _self

    @property
    def next(self) -> str:
        """Gets the next of this Links.


        :return: The next of this Links.
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next: str):
        """Sets the next of this Links.


        :param next: The next of this Links.
        :type next: str
        """

        self._next = next

    @property
    def prev(self) -> str:
        """Gets the prev of this Links.


        :return: The prev of this Links.
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev: str):
        """Sets the prev of this Links.


        :param prev: The prev of this Links.
        :type prev: str
        """

        self._prev = prev
