from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NoteCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, content=None):  # noqa: E501
        """NoteCreate - a model defined in OpenAPI

        :param title: The title of this NoteCreate.  # noqa: E501
        :type title: str
        :param content: The content of this NoteCreate.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'title': str,
            'content': str
        }

        self.attribute_map = {
            'title': 'title',
            'content': 'content'
        }

        self._title = title
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'NoteCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NoteCreate of this NoteCreate.  # noqa: E501
        :rtype: NoteCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this NoteCreate.


        :return: The title of this NoteCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NoteCreate.


        :param title: The title of this NoteCreate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def content(self) -> str:
        """Gets the content of this NoteCreate.


        :return: The content of this NoteCreate.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this NoteCreate.


        :param content: The content of this NoteCreate.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501
        if content is not None and len(content) < 1:
            raise ValueError("Invalid value for `content`, length must be greater than or equal to `1`")  # noqa: E501

        self._content = content
