from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.links import Links
from openapi_server.models.note import Note
from openapi_server.models.pagination import Pagination
from openapi_server import util

from openapi_server.models.links import Links  # noqa: E501
from openapi_server.models.note import Note  # noqa: E501
from openapi_server.models.pagination import Pagination  # noqa: E501

class NoteListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None, links=None):  # noqa: E501
        """NoteListResponse - a model defined in OpenAPI

        :param data: The data of this NoteListResponse.  # noqa: E501
        :type data: List[Note]
        :param pagination: The pagination of this NoteListResponse.  # noqa: E501
        :type pagination: Pagination
        :param links: The links of this NoteListResponse.  # noqa: E501
        :type links: Links
        """
        self.openapi_types = {
            'data': List[Note],
            'pagination': Pagination,
            'links': Links
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination',
            'links': 'links'
        }

        self._data = data
        self._pagination = pagination
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'NoteListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NoteListResponse of this NoteListResponse.  # noqa: E501
        :rtype: NoteListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Note]:
        """Gets the data of this NoteListResponse.


        :return: The data of this NoteListResponse.
        :rtype: List[Note]
        """
        return self._data

    @data.setter
    def data(self, data: List[Note]):
        """Sets the data of this NoteListResponse.


        :param data: The data of this NoteListResponse.
        :type data: List[Note]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this NoteListResponse.


        :return: The pagination of this NoteListResponse.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this NoteListResponse.


        :param pagination: The pagination of this NoteListResponse.
        :type pagination: Pagination
        """
        if pagination is None:
            raise ValueError("Invalid value for `pagination`, must not be `None`")  # noqa: E501

        self._pagination = pagination

    @property
    def links(self) -> Links:
        """Gets the links of this NoteListResponse.


        :return: The links of this NoteListResponse.
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links: Links):
        """Sets the links of this NoteListResponse.


        :param links: The links of this NoteListResponse.
        :type links: Links
        """

        self._links = links
